### ISSUE TITLE
Not woks on my pc

### ISSUE THREAD

**Issue by jimmy57000** [PlitherProject/Plither#1]
Hello,

i have this problem :

server not starting : http://prntscr.com/aq9dol

Client = OK 
Server = Not start .. 

Thanks, !

**Comment by mZer0ne** [comment]
Game server is in development stage

**Comment by eralpcicekdagi** [comment]
Hello how can put our server ips on i2.txt ?

**Comment by mZer0ne** [comment]
In the next update I gave up an encrypted type the IP address in the near future will open json

**Comment by eralpcicekdagi** [comment]
do you have facebook or something like that to getting online messaging

**Comment by mZer0ne** [comment]
@eralpcicekdagi, only VKontakte
https://vk.com/mzer0ne
