### ISSUE TITLE
Emulator

### ISSUE THREAD

**Issue by ElMay0r** [PlitherProject/Plither#10]
Will you release an Emu for this?

**Comment by ThunderGemios10** [comment]
Emulator? what are you talking about? This project is a server/client implementation for Slither.io, Meaning you can make your own private server.

**Comment by ElMay0r** [comment]
This is only to play on the original website?  I cant host my own wesite?

**Comment by ThunderGemios10** [comment]
@ElMay0r You can connect to the server with the original website.

**Comment by ElMay0r** [comment]
It would be nice if you can host your own webiste like Cigar (agario)

**Comment by ThunderGemios10** [comment]
@ElMay0r It would be, But that's illegal..

**Comment by mZer0ne** [comment]
What kind of law are you talking about? I'm from Ukraine)
