### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Logan7432** [PlitherProject/Plither#13]
I think it would be very cool to implement a chatbox like most agario private servers but for slither.io, for example Cigar agario on github is a great example for what this can turn out to be.

**Comment by ThunderGemios10** [comment]
A chat is a client-side, and making changes to client-side is illegal, However since Plither has made their own Slither.io client (Is also illegal), This should be possible.

**Comment by Logan7432** [comment]
Well would it illegal if you change the names and resigned the site to not look exactly like slither but do the same exact thing?

**Comment by Logan7432** [comment]
you might actually be able to take the code for the chat out of this https://github.com/CigarProject/Cigar but this is for agario

**Comment by ThunderGemios10** [comment]
@Logan7432 It is illegal since it looks like the real Slither.io, Having a slither.io clone is illegal... seriously.. This is Agar.io all over again..

**Comment by ThunderGemios10** [comment]
@Logan7432 That's Cigar, Another implementation that includes client, It is also illegal.. But they made it anyway.

**Comment by Logan7432** [comment]
@ThunderGemios10 Well if it is illegal, how come they didn't get in trouble for copyright?

**Comment by ThunderGemios10** [comment]
@Logan7432 It is illegal, Miniclip just doesn't care, Although they might find it sooner or later..
