### ISSUE TITLE
Can't connect to server?

### ISSUE THREAD

**Issue by RowanHarley** [PlitherProject/Plither#17]
I've just downloaded the latest release and started the server but when I went to connect with sos = [{ ip: "localhost", po: 443, ac: 34, ptm: 121 }] it wouldn't seem to connect! What am I doing wrong?

**Comment by ItzLevvie** [comment]
This is a client not a actual server.

**Comment by RowanHarley** [comment]
Where can I get a server?

**Comment by mZer0ne** [comment]
Server is still in the development stage

**Comment by RowanHarley** [comment]
Ok, so I'll just have to wait then will I?

**Comment by RowanHarley** [comment]
And by the way, why hasn't this repository been edited for about a week?

**Comment by ThunderGemios10** [comment]
@RowanHarley Either the developer is busy or he has abandoned it unannounced.. Or maybe he's still researching the protocol.

**Comment by matrixreal** [comment]
give him time ... so he will do great job
