### ISSUE TITLE
VPS 

### ISSUE THREAD

**Issue by GamerJam** [PlitherProject/Plither#18]
Hi guys. Sorry for bad english
I start the vps server but this letter to the console:

[Client] undefined is already in use
-------------------------------------------------------
[BATCH] Client Shutdown, waiting 15 seconds before a restart.

Help me!

**Comment by mZer0ne** [comment]
Use the `root` to run.
For ubuntu `sudo`

**Comment by GamerJam** [comment]
It did not work.

**Comment by mZer0ne** [comment]
What's your OS?
Какая у вас ОС?

**Comment by GamerJam** [comment]
Centos

**Comment by CreaModZ** [comment]
lol change the default port (80) to another in configs/ ...

**Comment by GamerJam** [comment]
It did not work...

**Comment by OldSparkyMI** [comment]
Change to port to something over 1024, e.g. to 8080.

**Comment by trilleplay** [comment]
Run the install_modules script then start the client.
