### ISSUE TITLE
GameServer Idea

### ISSUE THREAD

**Issue by mayed505** [PlitherProject/Plither#19]
Could you combine JSlither for the gameserver? or at least see its source code since its open-source? it would help you to make the game server get finished faster/

**Comment by redprogrammer** [comment]
I have been testted almost all opensource servers for Plither, only this worked for me but it has alot of bugs.

Serve for Plither: https://github.com/iiegor/slither

**Comment by RowanHarley** [comment]
[This JavaScript version](https://github.com/RowanHarley/Slither-Server) also works. This one is actively developed though

**Comment by mZer0ne** [comment]
@RowanHarley, Plither is now designed specifically for your development
