### ISSUE TITLE
Problem starting client - what do I wrong?

### ISSUE THREAD

**Issue by OldSparkyMI** [PlitherProject/Plither#20]
I always get
- `WebSocket connection to 'ws://78.46.43.244/ptc' failed: Connection closed before receiving a handshake response`
- `WebSocket connection to 'ws://149.56.20.78/ptc' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`
- `WebSocket connection to 'ws://176.9.64.19:443/slither' failed: WebSocket is closed before the connection is established.`

when I click on "PLAY".
My config is
`
{
	"serverPort": 80,
	"serverName": "Plither",
	"serverUrl": "localhost",
	"gameservers": [
		{
			"ip": "176.9.101.115",
			"po": 475
		}
	]
}
`

Can anyone help me - what do I do wrong?
Thx.

**Comment by herohamp** [comment]
are you sure the Plither gameserver works? because I though only the client worked

**Comment by ThunderGemios10** [comment]
The Plither GameServer does not work, and is under development.

**Comment by OldSparkyMI** [comment]
I entered under "gameservers" a live gameserver from slither.io - I thought thats the case for plither.
So what are the steps to run the client? How do I connect to a live slither.io game server?

**Comment by Marty25** [comment]
I'd also like to know how to connect to slither.io server :)
