### ISSUE TITLE
webpage

### ISSUE THREAD

**Issue by Logan7432** [PlitherProject/Plither#21]
Is there a awy to edit the html so i can customize the website? Also how do i hoest this publicly without using a localhost?

**Comment by herohamp** [comment]
You need to port forward your router

**Comment by herohamp** [comment]
Also the page is created with Javascript

**Comment by KSchreuder** [comment]
@Logan7432 the files can be found under **src/web/views ** these are .HBS files this are handlebars (templates) when you edit them its just **HTML**

**Comment by RowanHarley** [comment]
@Logan7432 you can use Hamachi to host slither publicly
