### ISSUE TITLE
Can not connect to server?

### ISSUE THREAD

**Issue by trilleplay** [PlitherProject/Plither#22]
Hello when I try to connect with the credentials I have entered it just keeps me on the loading screen. All of the credentials are correct. please fix this? I'm holding a gaming contest (maybe) and because of that I need the Plither Project. Please respond as soon as possible!

**Comment by ItzLevvie** [comment]
This is a client not a game server.

**Comment by trilleplay** [comment]
I know but you can set what server it is going to connect to by opening the config

**Comment by matrixreal** [comment]
Hi,
i got same problem ... with the console it gives an error
![slither](https://cloud.githubusercontent.com/assets/6823974/15950130/6dea6732-2eac-11e6-8ef5-9334ea3271a3.png)

**Comment by CalvinDKHD** [comment]
Its cause a game server isnt made yet, so its only the client. The server is not done.

**Comment by RowanHarley** [comment]
If you do need a server, you can have a look at [mine](https://github.com/RowanHarley/Slither-Server/).

**Comment by trilleplay** [comment]
Ive already have a server fixed but can not connect!

**Comment by RowanHarley** [comment]
Plither Project is only a client. You need a server as well so that you can play!
