### ISSUE TITLE
will you

### ISSUE THREAD

**Issue by eralpcicekdagi** [PlitherProject/Plither#4]
Will you add chatbox , skin uploader , background and like that adds

**Comment by Ciao121** [comment]
I vote to not add extras. I prefer if you leave it as basic. Maye, if this could be an option, think about a way to add those as plugins and not in the core.

**Comment by mZer0ne** [comment]
will add more repositories, it will remain with the original settings have extra lids which I copy, I will change them, the way the client and server will later be supplied separately!

**Comment by ThunderGemios10** [comment]
@Ciao121, How in the world are you able to extend the Core with plugins in Node.js?

**Comment by mZer0ne** [comment]
@ThunderGemios10, Implement structure can autocheck plugin you can!

**Comment by Ciao121** [comment]
@ThunderGemios10, I'm not a programmer so maybe the term I used (plugin) is not the best; I'm talking about taking the core as basic as the slither.io one and do not add features into it.
Taking as example ogar (agar.io server), I can imagine adding new entities or gamemodes as standalone file so the core is always the same and users can add something without touching it.

**Comment by ThunderGemios10** [comment]
@Ciao121 As of the moment, I never saw a Node.js software that can be extended with plugins, However i know that using Java would be possible, (*cough* Bukkit *cough*)

**Comment by eralpcicekdagi** [comment]
Some people dont know add chat etc plugins so if he do people can open or not open

**Comment by ThunderGemios10** [comment]
@eralpcicekdagi I have a chat packet in my Ogar 2 version... at https://github.com/OgarioProject
I'm not using it though..

**Comment by mZer0ne** [comment]
@ThunderGemios10, It may be enough of war? join forces?)

**Comment by ThunderGemios10** [comment]
@mZer0ne What do you mean war? Your actually thinking of competing? lol

**Comment by mZer0ne** [comment]
@ThunderGemios10 Let's do 2 projects simultaneously, one in java second on nodejs?
Давайте делать 2 проекта синхронно, Один на java второй на nodejs?


P.S. Sorry for my bad english) I'm from Ukraine)
P.S. Извините за мой плохой английский) Я с Украины)

**Comment by ThunderGemios10** [comment]
@mZer0ne I'm not how i can contribute to a project with a language that i don't know, For now i'll stick to Java. Since it has multi-threading..

**Comment by Ciao121** [comment]
You can collaborate sharing your knowledge (ie slither.io protocol, hints, etc) between you.

**Comment by ThunderGemios10** [comment]
@Ciao121 Good idea..

**Comment by eralpcicekdagi** [comment]
Yes too many guys need nodejs java is lookin us like a stranger

**Comment by ThunderGemios10** [comment]
@eralpcicekdagi Well, I'm not one of you "guys" I came from Bukkit, and i just discovered Agar.io and Slither.io, I'm using Java, You can take a look to my repos.

**Comment by eralpcicekdagi** [comment]
Ok.
