### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Sentaq** [PlitherProject/Plither#7]
Hello,

First of all, nice work! Keep it up!

I have some questions. Will you make it like a webclient (private server)? And also, will it work on Windows Server 2012?

Kind Regards,

Sentaq

**Comment by mZer0ne** [comment]
This is the Web Client, Node Js is a cross-platform application, and thus will work on Windows Server

**Comment by Sentaq** [comment]
So if I connect my VPS IP with my domain, people can play it through the domain? As a private server?

**Comment by mZer0ne** [comment]
Right! for this purpose and makes no client!

**Comment by Sentaq** [comment]
Ahh, alright. I was looking ages for this! Because with some servers you can only join like this: slither.io/VPSIP. And with this source with your own domain
