### ISSUE TITLE
How Can I Setup This

### ISSUE THREAD

**Issue by korlight** [PlitherProject/Plither#8]
Hi,

I can't find index.php file?

How can I setup?

Thank you very much.

**Comment by mZer0ne** [comment]
Hello, this is not php
Tomorrow will prepare the installation instructions.
1) Install [node.js](https://nodejs.org/en/download/) for your OS
2) Run the console (**Win + R** for windows)
3) Go to the folder of the console with PlitherProject (ex: C: \ Plither)
4) Perform `npm install` command to install modules
5) Start the server `npm start`
